---
  version: "2"

  services:
    korziliusweb:
      container_name: korzilius-web
      build: "."
      image: korzilius-web:latest
      links:
        - korziliusdb:db
        - korziliussockets:sockets
      volumes:
        - .:/var/www/html
      ports:
        - "80:80"
    korziliusdb:
      container_name: korzilius-db
      image: mysql:latest
      volumes:
        - database:/var/lib/mysql
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=korzilius
        - MYSQL_USER=korzilius
        - MYSQL_PASSWORD=korzilius
      ports:
        - "3306:3306"
    korziliussockets:
      environment:
        - API_PORT=50071
        - SOCKETS_PORT=50080
      container_name: korzilius-sockets
      build: docker/sockets/
      image: korzilius-sockets:latest
      ports:
        - "50080:50080"
    korziliuscache:
      container_name: korzilius-cache
      image: memcached:latest
  volumes:
    database:
      driver: local
    localfiles:
      driver: local
