<?= $this->doctype() ?>

<html>
  <head>
    <meta charset="utf-8">

<?php
echo $this->headTitle('Korzilius')
  ->setSeparator(' - ')
  ->setAutoEscape(false)
  ->toString(4);
?>

<?php
echo $this->headLink()
  ->prependStylesheet($this->basePath('assets/styles/style.min.css'))
  ->toString(4);
?>

<?php
echo $this->headScript()
  ->toString(4);
?>


  </head>
  <body>

    <?= $this->content ?>

<?php
echo $this->inlineScript()
  ->prependFile($this->basePath('assets/scripts/script.js'))
  ->toString(4);
?>


  </body>
</html>
